(function(E){function B(a,b){function c(){}c.prototype=a;a=new c;for(var e in b)a[e]=b[e];b.toString!==Object.prototype.toString&&(a.toString=b.toString);return a}var w=function(a,b){this.port=a;this.baudRate=b;this.isSending=this.connected=!1};w.__name__=["Controller"];w.prototype={connect:function(a,b){null==b&&(b=1E3);var c=this;this.serial=new F(this.port,{baudRate:this.baudRate,autoOpen:!0});this.serial.on("error",a);this.serial.on("disconnect",function(a){});this.serial.on("data",function(a){});
this.serial.on("open",function(){c.connected=!0;c.sendBuffer=[];null==b||0==b?a(null):n.delay(function(){a(null)},b)})},disconnect:function(a){this.connected?(this.connected=!1,this.sendBuffer=[],this.serial.close(a)):a()},setColor:function(a,b){var c=this,e=new ArrayBuffer(3);(new Uint8Array(e)).set([a>>16&255,a>>8&255,a&255]);this.serial.write(new G(e),null,function(e){null!=e?null!=b&&b(e):c.serial.flush(function(e){null!=e?null!=b&&b(e):(c.isSending=!1,c.lastSentColor=a,0<c.sendBuffer.length&&
(e=c.sendBuffer.shift(),c.setColor(e)))})})},__class__:w};var y=function(a,b){this.r=new RegExp(a,b.split("u").join(""))};y.__name__=["EReg"];y.prototype={match:function(a){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(a);this.r.s=a;return null!=this.r.m},matched:function(a){if(null!=this.r.m&&0<=a&&a<this.r.m.length)return this.r.m[a];throw new p("EReg::matched");},__class__:y};var m=function(){};m.__name__=["HxOverrides"];m.cca=function(a,b){a=a.charCodeAt(b);if(a==a)return a};m.substr=
function(a,b,c){if(null==c)c=a.length;else if(0>c)if(0==b)c=a.length+c;else return"";return a.substr(b,c)};var d=function(){};d.__name__=["Main"];d.activate=function(a){null==a&&(a={color:2117979,settings:{open:!1}});d.allowedDevices=[];d.controllers=[];d.dirty=!0;d.color=a.color;d.settings=new z(d.color,d.changeColor,a.settings.open);a=atom.config.get("darkside.device");null!=a&&0!=a.length&&(d.allowedDevices.push(a),n.delay(function(){d.searchControllers(function(a,c){null!=a?atom.notifications.addError(a.message):
(d.controllers=c,n.delay(function(){d.changeColor(d.color)},500),atom.commands.add("atom-workspace","darkside:off",function(a){d.changeColor(0)}),atom.commands.add("atom-workspace","darkside:darker",function(a){a=d.color;a=v.darker([(a>>16&255)/255,(a>>8&255)/255,(a&255)/255],.1);d.changeColor((Math.round(255*a[0])&255)<<16|(Math.round(255*a[1])&255)<<8|Math.round(255*a[2])&255)}),atom.commands.add("atom-workspace","darkside:lighter",function(a){a=d.color;a=v.lighter([(a>>16&255)/255,(a>>8&255)/255,
(a&255)/255],.1);d.changeColor((Math.round(255*a[0])&255)<<16|(Math.round(255*a[1])&255)<<8|Math.round(255*a[2])&255)}),atom.commands.add("atom-workspace","darkside:settings",function(a){a=d.settings;a.panel.isVisible()?a.panel.hide():a.panel.show()}),d.timer=new n(16),d.timer.run=d.handleTimer)})},atom.config.get("darkside.startdelay")))};d.deactivate=function(){null!=d.timer&&d.timer.stop();d.settings.panel.destroy();for(var a=0,b=d.controllers;a<b.length;){var c=b[a];++a;c.disconnect()}};d.serialize=
function(){return{color:d.color,settings:d.settings.serialize()}};d.handleTimer=function(){if(d.dirty){for(var a=0,b=d.controllers;a<b.length;){var c=b[a];++a;c.setColor(d.color)}d.dirty=!1}};d.changeColor=function(a){a!=d.color&&(d.color=a,d.dirty=!0)};d.searchControllers=function(a){require("serialport").list(function(b,c){if(null!=b)a(b);else{var e=[];for(b=0;b<c.length;){var x=c[b];++b;for(var f=!1,g=0,D=d.allowedDevices;g<D.length;){var t=D[g];++g;if(x.serialNumber==t){f=!0;break}}f&&e.push(x)}var l=
0,h=[];for(c=0;c<e.length;)b=e[c],++c,b=[new w(b.comName,atom.config.get("darkside.baud_rate"))],x=function(b){return function(c){null!=c?a(c):(h.push(b[0]),(l+=1)==e.length&&a(null,h))}}(b),b[0].connect(x)}})};d.provideService=function(){return{get:function(){return d.color},set:function(a,b){d.changeColor(a)}}};d.getConfigValue=function(a){return atom.config.get("darkside."+a)};Math.__name__=["Math"];var z=function(a,b,c){null==c&&(c=!1);var e=this;this.color=a;this.onChange=b;this.element=window.document.createElement("div");
this.element.classList.add("darkside-settings");this.preview=window.document.createElement("input");this.preview.type="text";this.preview.classList.add("preview","input-text");this.element.appendChild(this.preview);var d=function(a,b,c,e,d){null==d&&(d=0);null==e&&(e=.01);null==c&&(c=1);null==b&&(b=0);var f=window.document.createElement("input");null!=a&&(f.title=a,f.name=a);f.type="range";f.classList.add("input-range");f.min=null==b?"null":""+b;f.max=null==c?"null":""+c;f.step=null==e?"null":""+
e;f.value=null==d?"null":""+d;return f},f=window.document.createElement("section");f.appendChild(d("r",0,255,1,a>>16&255));f.appendChild(d("g",0,255,1,a>>8&255));f.appendChild(d("b",0,255,1,a&255));this.element.appendChild(f);f.addEventListener("input",function(c){var d=q.parseInt(c.target.value);try{a=I.setChannel(a,q.string(c.target.name),d)}catch(t){g.lastException=t;window.console.error((t instanceof p?t.val:t).toString());return}e.setColor(a);b(a)});f=window.document.createElement("section");
f.appendChild(d("h",0,359,1,v.toHSV([(a>>16&255)/255,(a>>8&255)/255,(a&255)/255])[0]));f.appendChild(d("s",0,1,.01,v.toHSV([(a>>16&255)/255,(a>>8&255)/255,(a&255)/255])[1]));f.appendChild(d("v",0,1,.01,v.toHSV([(a>>16&255)/255,(a>>8&255)/255,(a&255)/255])[2]));this.element.appendChild(f);this.setColor(a);this.panel=atom.workspace.addFooterPanel({item:this.element,visible:c})};z.__name__=["SettingsView"];z.prototype={serialize:function(){return{open:this.panel.isVisible()}},setColor:function(a){this.color=
a;a="#"+k.hex(a>>16&255,2)+k.hex(a>>8&255,2)+k.hex(a&255,2);this.preview.value=a;this.preview.style.background=a},__class__:z};var q=function(){};q.__name__=["Std"];q.string=function(a){return h.__string_rec(a,"")};q.parseInt=function(a){var b=parseInt(a,10);0!=b||120!=m.cca(a,1)&&88!=m.cca(a,1)||(b=parseInt(a));return isNaN(b)?null:b};var A=function(){this.b=""};A.__name__=["StringBuf"];A.prototype={__class__:A};var k=function(){};k.__name__=["StringTools"];k.isSpace=function(a,b){a=m.cca(a,b);return 8<
a&&14>a?!0:32==a};k.ltrim=function(a){for(var b=a.length,c=0;c<b&&k.isSpace(a,c);)++c;return 0<c?m.substr(a,c,b-c):a};k.rtrim=function(a){for(var b=a.length,c=0;c<b&&k.isSpace(a,b-c-1);)++c;return 0<c?m.substr(a,0,b-c):a};k.trim=function(a){return k.ltrim(k.rtrim(a))};k.hex=function(a,b){for(var c="";c="0123456789ABCDEF".charAt(a&15)+c,a>>>=4,0<a;);if(null!=b)for(;c.length<b;)c="0"+c;return c};var C=function(){};C.__name__=["Type"];C.getClassName=function(a){a=a.__name__;return null==a?null:a.join(".")};
var l={__ename__:!0,__constructs__:["CFunction","Module","FilePos","Method","LocalFunction"],CFunction:["CFunction",0]};l.CFunction.__enum__=l;l.Module=function(a){a=["Module",1,a];a.__enum__=l;return a};l.FilePos=function(a,b,c,e){a=["FilePos",2,a,b,c,e];a.__enum__=l;return a};l.Method=function(a,b){a=["Method",3,a,b];a.__enum__=l;return a};l.LocalFunction=function(a){a=["LocalFunction",4,a];a.__enum__=l;return a};var g=function(){};g.__name__=["haxe","CallStack"];g.getStack=function(a){if(null==
a)return[];var b=Error.prepareStackTrace;Error.prepareStackTrace=function(a,b){a=[];for(var c=0;c<b.length;){var e=b[c];++c;null!=g.wrapCallSite&&(e=g.wrapCallSite(e));var d=null,h=e.getFunctionName();if(null!=h){var k=h.lastIndexOf(".");0<=k&&(d=m.substr(h,0,k),h=m.substr(h,k+1,null),d=l.Method(d,h))}a.push(l.FilePos(d,e.getFileName(),e.getLineNumber(),e.getColumnNumber()))}return a};a=g.makeStack(a.stack);Error.prepareStackTrace=b;return a};g.callStack=function(){try{throw Error();}catch(b){g.lastException=
b;var a=g.getStack(b);a.shift();return a}};g.exceptionStack=function(){return g.getStack(g.lastException)};g.toString=function(a){for(var b=new A,c=0;c<a.length;){var e=a[c];++c;b.b+="\nCalled from ";g.itemToString(b,e)}return b.b};g.itemToString=function(a,b){switch(b[1]){case 0:a.b+="a C function";break;case 1:b=b[2];a.b+="module ";a.b+=null==b?"null":""+b;break;case 2:var c=b[5],e=b[4],d=b[3];b=b[2];null!=b&&(g.itemToString(a,b),a.b+=" (");a.b+=null==d?"null":""+d;a.b+=" line ";a.b+=null==e?"null":
""+e;null!=c&&(a.b+=" column ",a.b+=null==c?"null":""+c);null!=b&&(a.b+=")");break;case 3:c=b[3];b=b[2];a.b+=null==b?"null":""+b;a.b+=".";a.b+=null==c?"null":""+c;break;case 4:b=b[2],a.b+="local function #",a.b+=null==b?"null":""+b}};g.makeStack=function(a){if(null==a)return[];if("string"==typeof a){a=a.split("\n");"Error"==a[0]&&a.shift();for(var b=[],c=new y("^   at ([A-Za-z0-9_. ]+) \\(([^)]+):([0-9]+):([0-9]+)\\)$",""),e=0;e<a.length;){var d=a[e];++e;if(c.match(d)){d=c.matched(1).split(".");var f=
d.pop(),g=c.matched(2),h=q.parseInt(c.matched(3)),m=q.parseInt(c.matched(4));b.push(l.FilePos("Anonymous function"==f?l.LocalFunction():"Global code"==f?null:l.Method(d.join("."),f),g,h,m))}else b.push(l.Module(k.trim(d)))}return b}return a};var n=function(a){var b=this;this.id=setInterval(function(){b.run()},a)};n.__name__=["haxe","Timer"];n.delay=function(a,b){var c=new n(b);c.run=function(){c.stop();a()};return c};n.prototype={stop:function(){null!=this.id&&(clearInterval(this.id),this.id=null)},
run:function(){},__class__:n};var p=function(a){Error.call(this);this.val=a;this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,p)};p.__name__=["js","_Boot","HaxeError"];p.wrap=function(a){return a instanceof Error?a:new p(a)};p.__super__=Error;p.prototype=B(Error.prototype,{__class__:p});var h=function(){};h.__name__=["js","Boot"];h.getClass=function(a){if(a instanceof Array&&null==a.__enum__)return Array;var b=a.__class__;if(null!=b)return b;a=h.__nativeClassName(a);return null!=
a?h.__resolveNativeClass(a):null};h.__string_rec=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.__name__||a.__ename__)&&(c="object");switch(c){case "function":return"<function>";case "object":if(a instanceof Array){if(a.__enum__){if(2==a.length)return a[0];c=a[0]+"(";b+="\t";for(var e=2,d=a.length;e<d;){var f=e++;c=2!=f?c+(","+h.__string_rec(a[f],b)):c+h.__string_rec(a[f],b)}return c+")"}c=a.length;e="[";b+="\t";for(d=0;d<c;)f=d++,e+=(0<f?",":"")+
h.__string_rec(a[f],b);return e+"]"}try{e=a.toString}catch(H){return g.lastException=H,"???"}if(null!=e&&e!=Object.toString&&"function"==typeof e&&(c=a.toString(),"[object Object]"!=c))return c;c=null;e="{\n";b+="\t";d=null!=a.hasOwnProperty;for(c in a)d&&!a.hasOwnProperty(c)||"prototype"==c||"__class__"==c||"__super__"==c||"__interfaces__"==c||"__properties__"==c||(2!=e.length&&(e+=", \n"),e+=b+c+" : "+h.__string_rec(a[c],b));b=b.substring(1);return e+("\n"+b+"}");case "string":return a;default:return String(a)}};
h.__nativeClassName=function(a){a=h.__toStr.call(a).slice(8,-1);return"Object"==a||"Function"==a||"Math"==a||"JSON"==a?null:a};h.__resolveNativeClass=function(a){return E[a]};var G=require("buffer").Buffer,F=require("serialport"),r=function(a,b,c){Error.call(this,a);this.message=a;a=C.getClassName(h.getClass(this));-1!=a.indexOf(".")&&(a=a.split(".").pop());this.name=a;this.pos=c;if(null==b){try{b=g.exceptionStack()}catch(e){g.lastException=e,b=[]}if(0==b.length)try{b=g.callStack()}catch(e){g.lastException=
e,b=[]}}this.stackItems=b};r.__name__=["om","Error"];r.__super__=Error;r.prototype=B(Error.prototype,{toString:function(){var a=g.exceptionStack();0==a.length&&(a=g.callStack());return this.pos.fileName+":"+this.pos.lineNumber+" : "+this.message+g.toString(a)},__class__:r});var I={__name__:["om","color","space","_RGB","RGB_Impl_"],setChannel:function(a,b,c){switch(b.toLowerCase()){case "b":case "blue":b=2;break;case "g":case "green":b=1;break;case "r":case "red":b=0;break;default:throw new u(b,null,
{fileName:"om/color/space/RGB.hx",lineNumber:86,className:"om.color.space._RGB.RGB_Impl_",methodName:"setChannel"});}switch(b){case 0:a=[c,a>>8&255,a&255];break;case 1:a=[a>>16&255,c,a&255];break;case 2:a=[a>>16&255,a>>8&255,c];break;default:throw new u(b,null,{fileName:"om/color/space/RGB.hx",lineNumber:68,className:"om.color.space._RGB.RGB_Impl_",methodName:"set"});}return(a[0]&255)<<16|(a[1]&255)<<8|a[2]&255}},v={__name__:["om","color","space","_RGBX","RGBX_Impl_"],darker:function(a,b){var c=a[0],
e=a[1];a=a[2];return[(0-c)*b+c,(0-e)*b+e,(0-a)*b+a]},lighter:function(a,b){var c=a[0],e=a[1];a=a[2];return[(1-c)*b+c,(1-e)*b+e,(1-a)*b+a]},toHSV:function(a){var b=a[0],c=a[1];b=b>c?c:b;c=a[2];var e=a[0],d=a[1];e=e<d?d:e;d=a[2];e=e<d?d:e;b=e-(b>c?c:b);if(0==b)return[-1,0,e];a=a[0]==e?(a[1]-a[2])/b:a[1]==e?2+(a[2]-a[0])/b:4+(a[0]-a[1])/b;a*=60;0>a&&(a+=360);return[a,b/e,e]}},u=function(a,b,c){var d="out of bounds "+q.string(a);null!=b&&(d+=" expected "+q.string(b));r.call(this,d,null,c);this.value=
a;this.expected=b};u.__name__=["om","error","OutOfBounds"];u.__super__=r;u.prototype=B(r.prototype,{__class__:u});module.exports=d;String.prototype.__class__=String;String.__name__=["String"];Array.__name__=["Array"];h.__toStr={}.toString})("undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this);
